services:
  craftystatus:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - craftystatus:dev
    environment:
      - NODE_ENV=development # more logging
    ports:
      - "5555:5555" # Prisma Studio
    healthcheck:
      interval: 3s
  db:
    ports:
      - 5432:5432
